### ISSUE TITLE
Power buttons are truncated

### ISSUE THREAD

**Issue by R3D2** [LinxGem33/Arc-Menu#10]
![screenshot from 2017-05-24 12-17-03](https://cloud.githubusercontent.com/assets/5547320/26398800/f3765d9e-407a-11e7-893a-b58d2d0ed5c6.png)

**Comment by ankurk91** [comment]
Same here.
Using [Arc theme](https://github.com/horst3180/arc-theme) on Ubuntu 17.04.
Installed Arc Menu from extensions store.

![screenshot from 2017-05-24 17-13-30](https://cloud.githubusercontent.com/assets/6111524/26401706/c7b427ca-40a4-11e7-8e62-f41eb81ce7ce.png)

**Comment by LinxGem33** [comment]
@R3D2  @ankurk91 

appreciate the feed back, this issue has been fixed ill be uploading to extensions.gnome.org shortly so keep an eye out for the update.

please see #9 

kind regards

**Comment by vortex09** [comment]
Sorry but this problem is still present with the latest version of Arc theme (updated 14 days ago)
