### ISSUE TITLE
Can't log back in after locking screen

### ISSUE THREAD

**Issue by edgarlpassos** [LinxGem33/Arc-Menu#209]
Using Arc Menu on Gnome Shell 3.26.2 on Arch Linux
With the screen locked, gdm doesn't respond and I can't log back in. I have to switch to a different tty and change back to get to the login screen and be able to log in. Some times, after logging in, GNOME has to restart.
I have disabled all other extensions to trace this back to Arc Menu.

**Comment by LinxGem33** [comment]
appreciate the feedback, could you give us  **Full Logs from the systemd journal**:
```
journalctl /usr/bin/gnome-shell -f -o cat
```
For more details see:
[Supporting Information](https://github.com/LinxGem33/Arc-Menu/wiki/Supporting-Information)

also if you can make sure you have all the dependencies installed:
[Gnome Dependencies](https://github.com/LinxGem33/Arc-Menu/wiki/Supported-Distributions#gnome-dependencies)

also could you let us know how you installed the extension i.e via gnome extensions website or the AUR etc.

kind regards

**Comment by edgarlpassos** [comment]
Hi! 

I installed the extension via the gnome extensions website
Here are the logs:

```
clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
g_object_set: assertion 'G_IS_OBJECT (object)' failed
g_object_set: assertion 'G_IS_OBJECT (object)' failed
clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
g_object_set: assertion 'G_IS_OBJECT (object)' failed
g_object_set: assertion 'G_IS_OBJECT (object)' failed
clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
WARNING: addSignalMethods is replacing existing [0x563053a89440 Gjs_ShowAppsIcon.dash-item-container] connect method
WARNING: addSignalMethods is replacing existing [0x563053a89440 Gjs_ShowAppsIcon.dash-item-container] disconnect method
WARNING: addSignalMethods is replacing existing [0x563053a89440 Gjs_ShowAppsIcon.dash-item-container] emit method
```

**Comment by LinxGem33** [comment]
hi 

I've thoroughly tested on Gnome Shell 3.26.2 on Arch Linux and i am unable to replicate this issue my suggestion is to try and install from source i suspect you may have another issue on your system which maybe affecting your system.

**install from source instructions**

[Install from source ](https://github.com/LinxGem33/Arc-Menu/wiki/Installing-from-extensions.gnome.org#manual-installuninstall-using-make)
##
kind regards

**Comment by LinxGem33** [comment]
going to set this issue with a medium priority as it seems to be related to these issues and also seems to be affecting Arch based distros running gnome shell 3.26.2, will be logged for further investigation.

#215  #212 #209

**Comment by LinxGem33** [comment]
this issue should now be fixed #218 please install from the latest master branch and let me know if it has indeed fixed the issue on your systems.

**Comment by edgarlpassos** [comment]
Hello, @LinxGem33 
Thanks for the attention! I installed from the master branch but unfortunately I'm still experiencing the problems I described earlier. I removed lightdm completely earlier, as you suggested.

Using 

```
journalctl /usr/bin/gnome-shell -f -o cat
```

This output, which I think is relevant, appears repeatedly:

```
Object St.BoxLayout (0x55c39b28c800), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
== Stack trace for context 0x55c398a01170 ==
#0 0x7ffe7968e2a0 b   /home/epassos/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/menu.js:266 (0x7f30cfef1670 @ 372)
#1 0x7ffe7968e300 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f30d6ec2bc0 @ 71)
#2 0x7ffe7968e3a0 b   /home/epassos/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/menu.js:619 (0x7f30cfef1d58 @ 98)
#3 0x7ffe7968e400 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f30d6ec2bc0 @ 71)
#4 0x7ffe7968e4a0 b   /home/epassos/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/menu.js:222 (0x7f30cfef1560 @ 53)
#5 0x7ffe7968e500 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f30d6ec2bc0 @ 71)
#6 0x7ffe7968e5a0 b   /home/epassos/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/menu.js:152 (0x7f30cfef1120 @ 17)
#7 0x7ffe7968e630 I   self-hosted:917 (0x7f30d6eee5e8 @ 394)
#8 0x55c398fe3660 i   /home/epassos/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:267 (0x7f30cfe71340 @ 837)
#9 0x7ffe79690530 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f30d6ec2bc0 @ 71)
#10 0x55c398fe35a8 i   /home/epassos/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:97 (0x7f30cfe62e68 @ 28)
#11 0x7ffe796912c0 b   resource:///org/gnome/shell/ui/extensionSystem.js:82 (0x7f30d6cb4230 @ 431)
#12 0x7ffe79691360 b   resource:///org/gnome/shell/ui/extensionSystem.js:344 (0x7f30d6cb4cd0 @ 13)
#13 0x7ffe796913c0 I   self-hosted:251 (0x7f30d6ed25e8 @ 223)
#14 0x55c398fe3528 i   resource:///org/gnome/shell/ui/extensionSystem.js:343 (0x7f30d6cb4c48 @ 63)
#15 0x55c398fe34a8 i   resource:///org/gnome/shell/ui/extensionSystem.js:361 (0x7f30d6cb4d58 @ 87)
#16 0x7ffe79692200 I   resource:///org/gnome/gjs/modules/signals.js:126 (0x7f30d6ee2b38 @ 386)
#17 0x7ffe796922c0 b   resource:///org/gnome/shell/ui/sessionMode.js:204 (0x7f30d60a31a8 @ 254)
#18 0x7ffe79692320 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f30d6ec2bc0 @ 71)
clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
#19 0x55c398fe3420 i   resource:///org/gnome/shell/ui/sessionMode.js:166 (0x7f30d609def0 @ 40)
#20 0x7ffe79692f60 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f30d6ec2bc0 @ 71)
#21 0x55c398fe3378 i   resource:///org/gnome/shell/ui/screenShield.js:1281 (0x7f30d60771a8 @ 188)
#22 0x7ffe79693ba0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f30d6ec2bc0 @ 71)
#23 0x55c398fe32c8 i   resource:///org/gnome/shell/ui/screenShield.js:1327 (0x7f30d6077230 @ 391)
#24 0x7ffe796947e0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f30d6ec2bc0 @ 71)
#25 0x55c398fe3220 i   resource:///org/gnome/shell/ui/shellDBus.js:462 (0x7f30d6089560 @ 82)
#26 0x7ffe79695430 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f30d6ec2bc0 @ 71)
#27 0x55c398fe3158 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:300 (0x7f30d6c06230 @ 614)
#28 0x55c398fe30b0 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:331 (0x7f30d6c06450 @ 34)
```

**Comment by LinxGem33** [comment]
hi appreciate the feed back, i can confirm with the new patch #218 it resolves the issue with the lock sleep and suspend function, so im not sure what the issue maybe on your system as i have tested on arch specifically for all three issues and it is now fixed with this patch looking at the logs i cant really see anything pointing to arc menu as the cause of your issue.

maybe try install gdm and enable it again and then restart your system.

**Comment by edgarlpassos** [comment]
Still no luck after all the suggested steps...


The output of  `journalctl /usr/bin/gnome-shell -f -o cat` has changed, however.

```
== Stack trace for context 0x55b3591c4170 ==
#0 0x7ffd8fa8b710 b   /home/epassos/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:338 (0x7f405289e120 @ 38)
#1 0x7ffd8fa8b770 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f40a02c2bc0 @ 71)
#2 0x7ffd8fa8b860 b   /home/epassos/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:428 (0x7f405289e780 @ 212)
#3 0x7ffd8fa8b8f0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f40a02c2bc0 @ 71)
#4 0x7ffd8fa8b990 b   /home/epassos/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:403 (0x7f405289e4d8 @ 17)
#5 0x7ffd8fa8ba00 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f40a02c2bc0 @ 71)
#6 0x7ffd8fa8ba60 I   self-hosted:917 (0x7f40a02ee5e8 @ 394)
#7 0x55b3597a76f0 i   resource:///org/gnome/shell/ui/main.js:544 (0x7f40a02f6a28 @ 209)
#8 0x55b3597a7620 i   /home/epassos/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:901 (0x7f40528a0120 @ 457)
#9 0x55b3597a7548 i   /home/epassos/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:603 (0x7f405289eab0 @ 1321)
#10 0x7ffd8fa8deb0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f40a02c2bc0 @ 71)
#11 0x55b3597a74c0 i   resource:///org/gnome/shell/ui/appDisplay.js:1751 (0x7f40945e3670 @ 35)
#12 0x7ffd8fa8eb00 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f40a02c2bc0 @ 71)
#13 0x7ffd8fa8eb60 I   self-hosted:917 (0x7f40a02ee5e8 @ 394)
```

**Comment by charlesg99** [comment]
Hey @edgarlpassos, seems like theses new warnings are coming from dash to panel.

Some corrections for this issue were submitted to jderose9/dash-to-panel#344, but they haven't been merged yet. Until then, if you want you could install dash to panel from this [fork](https://github.com/charlesg99/dash-to-panel) and see if that solves the problem.

Also, this issue has already been reported to dash to panel (jderose9/dash-to-panel#338), if you want to contribute to it or stay updated on its progress.

Thanks a bunch!

**Comment by edgarlpassos** [comment]
Hey @charlesg99, thanks for your response! I tried installing your fork, but I still encounter the same problems, albeit with some different outputs. Should I fill an issue on your repo?

**Comment by charlesg99** [comment]
Could you please edit your last comment with the logs you're getting? Thanks

**Comment by LinxGem33** [comment]
hi edgarlpassos , Im confident now that this issue has now been fixed on the arch distro on gnome shell 3.26.2 as Ive tested all the functions regarding **suspend** ,**Lock** ,**Sleep** and all are working as expected also other users who had similar issues now report that the issue has been fixed with the latest patch etc.

i think you may have another underlying issue on your system which is affecting your  gdm lock function as arch is a rolling release and as such inherently not classed as stable due to the ever updating packages, so you may need to investigate.

**Comment by charlesg99** [comment]
@edgarlpassos I also believe that the Arc-Menu issue can be closed. The dash to panel fixes have been merge so please report your problematic out

**Comment by edgarlpassos** [comment]
@LinxGem33 @charlesg99 From the logs I am satisfied that the issues related to Arc Menu are fixed, I will report my issues on the Dash to Panel repo.
I think you can close this issue. Thanks for the attention!
